apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-openems
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: docs
      defaultBucket: openems
    secureJsonData:
      token: $INFLUXDB_TOKEN
