#!/usr/bin/env python3
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUNDLE = HERE.parent
SIMULATOR = BUNDLE.parent.parent / "heat-pump-simulator"
DEFAULT_JSON = (SIMULATOR / "sim" / "adress_lists"
                / "IDM_Navigator_Modbus_TCP_Parameterliste.json")
sys.path.insert(0, str(SIMULATOR))
from sim.physics.buffer_registers import BUFFER_BOTTOM_ADDR, BUFFER_TOP_ADDR
from sim.physics.clock.clock_register import CLOCK_FACTOR_ADDR
from sim.physics.cop_register import COP_ADDR
from sim.physics.synthetic_registers import synthetic_registers

PKG = "io.openems.edge.heatpump.idm"
SRC = BUNDLE / "src" / "io" / "openems" / "edge" / "heatpump" / "idm"

MAX_BLOCK_REGS = 100  # Modbus allows up to 125 registers per transaction

HIGH_PRIORITY_ADDRS = {1000, 1002, 1008, 1091, 1050, 1052, 1104, 1378, 1393, 1415, 1429, 1442, 1790, 1005, 1032,
                       1401, 1449, 1491, 1710, 1711, 1712,
                       4122, CLOCK_FACTOR_ADDR, BUFFER_TOP_ADDR, BUFFER_BOTTOM_ADDR, COP_ADDR}

# DataType -> (OpenemsType, Java element expression template, register width)
TYPE_MAP = {
    "FLOAT": ("FLOAT", "new FloatDoublewordElement({a}).wordOrder(LSWMSW)", 2),
    "WORD":  ("INTEGER", "new SignedWordElement({a})", 1),
    "UCHAR": ("INTEGER", "new UnsignedWordElement({a})", 1),
    "BOOL":  ("INTEGER", "new UnsignedWordElement({a})", 1),
}


def esc(text):
    """Make the text safe for a Java string literal."""
    text = text.replace("\\", "\\\\").replace('"', '\\"')
    text = re.sub(r"\s+", " ", text).strip()
    return text


def load(path):
    raw = Path(path).read_bytes()
    return json.loads(raw.decode("utf-8"))


def numeric_limit(value):
    if isinstance(value, bool):
        return ""
    if isinstance(value, (int, float)):
        return value
    try:
        return float(str(value).strip().replace(",", "."))
    except ValueError:
        return ""


def normalize(entry):
    """Reduce a raw JSON entry to what the generator needs."""
    dtype = entry["DataType"].strip().upper()
    access = entry["Access"].strip().upper().replace("/RO", "").replace("RO/", "")
    # RW/RO -> RW; plain RO/RW/W stay as they are
    if access not in ("RO", "RW", "W"):
        access = "RW" if "W" in access else "RO"
    otype, tmpl, width = TYPE_MAP[dtype]
    name = entry.get("Name", "").strip() or f"Register {entry['Address']}"
    unit = entry.get("Unit", "").strip()
    label = f"{name} [{unit}]" if unit else name
    return {
        "addr": int(entry["Address"]),
        "dtype": dtype,
        "access": access,
        "otype": otype,
        "tmpl": tmpl,
        "width": width,
        "cid": f"REG_{int(entry['Address'])}",
        "label": esc(label),
        "name": esc(name),
        "unit": unit,
        "min": numeric_limit(entry.get("Min", "")),
        "max": numeric_limit(entry.get("Max", "")),
        "valueList": entry.get("ValueList", "").strip() if isinstance(entry.get("ValueList", ""), str) else "",
    }


def group_contiguous(regs):
    blocks = []
    cur = []
    cursor = None
    for r in sorted(regs, key=lambda x: x["addr"]):
        block_regs = sum(x["width"] for x in cur)
        if cur and r["addr"] == cursor and block_regs + r["width"] <= MAX_BLOCK_REGS:
            cur.append(r)
        else:
            if cur:
                blocks.append(cur)
            cur = [r]
        cursor = r["addr"] + r["width"]
    if cur:
        blocks.append(cur)
    return blocks


def range_check(r):
    """Java expression rejecting write values outside the specified range."""
    if r["access"] == "RO":
        return None
    if r["min"] == "" or r["max"] == "":
        return f'RegisterRange.finite("{r["name"]}")'
    return f'RegisterRange.limit("{r["name"]}", {float(r["min"])}, {float(r["max"])})'


def gen_interface(regs):
    lines = []
    lines.append(f"package {PKG};")
    lines.append("")
    lines.append("import io.openems.common.channel.AccessMode;")
    lines.append("import io.openems.common.types.OpenemsType;")
    lines.append("import io.openems.edge.common.channel.Doc;")
    lines.append("import io.openems.edge.common.component.OpenemsComponent;")
    lines.append("")
    lines.append("/** AUTO-GENERATED by generator/generate.py - do not edit by hand. */")
    lines.append("public interface HeatpumpIdm extends OpenemsComponent {")
    lines.append("")
    lines.append("\tpublic enum ChannelId implements io.openems.edge.common.channel.ChannelId {")
    for r in regs:
        if r["access"] == "RO":
            acc = "READ_ONLY"
        elif r["access"] == "W":
            acc = "WRITE_ONLY"
        else:
            acc = "READ_WRITE"
        lines.append(
            f'\t\t{r["cid"]}(Doc.of(OpenemsType.{r["otype"]}) //'
        )
        lines.append(f'\t\t\t\t.accessMode(AccessMode.{acc}) //')
        check = range_check(r)
        if check is None:
            lines.append(f'\t\t\t\t.text("{r["label"]}")), //')
        else:
            lines.append(f'\t\t\t\t.text("{r["label"]}") //')
            lines.append(f'\t\t\t\t.onInit({check})), //')
    lines.append("\t\t;")
    lines.append("")
    lines.append("\t\tprivate final Doc doc;")
    lines.append("")
    lines.append("\t\tprivate ChannelId(Doc doc) {")
    lines.append("\t\t\tthis.doc = doc;")
    lines.append("\t\t}")
    lines.append("")
    lines.append("\t\t@Override")
    lines.append("\t\tpublic Doc doc() {")
    lines.append("\t\t\treturn this.doc;")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def elem(r):
    return r["tmpl"].format(a=r["addr"])


def gen_read_task(fc_class, priority, block):
    inner = ",\n".join(
        f'\t\t\t\tm(HeatpumpIdm.ChannelId.{r["cid"]}, {elem(r)})' for r in block
    )
    start = block[0]["addr"]
    return (f'\t\tnew {fc_class}({start}, Priority.{priority},\n'
            f'{inner})')


def gen_write_task(block):
    inner = ",\n".join(
        f'\t\t\t\tm(HeatpumpIdm.ChannelId.{r["cid"]}, {elem(r)})' for r in block
    )
    start = block[0]["addr"]
    return f'\t\tnew FC16WriteRegistersTask({start},\n{inner})'


def gen_impl(regs):
    ro = [r for r in regs if r["access"] == "RO"]
    rw = [r for r in regs if r["access"] == "RW"]
    writable = [r for r in regs if r["access"] in ("RW", "W")]

    def split_by_priority(registers):
        high = [r for r in registers if r["addr"] in HIGH_PRIORITY_ADDRS]
        low = [r for r in registers if r["addr"] not in HIGH_PRIORITY_ADDRS]
        return high, low

    ro_high, ro_low = split_by_priority(ro)
    rw_high, rw_low = split_by_priority(rw)

    tasks = []
    for block in group_contiguous(ro_high):
        tasks.append(gen_read_task("FC4ReadInputRegistersTask", "HIGH", block))
    for block in group_contiguous(ro_low):
        tasks.append(gen_read_task("FC4ReadInputRegistersTask", "LOW", block))
    for block in group_contiguous(rw_high):
        tasks.append(gen_read_task("FC3ReadRegistersTask", "HIGH", block))
    for block in group_contiguous(rw_low):
        tasks.append(gen_read_task("FC3ReadRegistersTask", "LOW", block))
    for block in group_contiguous(writable):
        tasks.append(gen_write_task(block))

    body = ",\n".join(tasks)

    return f"""package {PKG};

import static io.openems.edge.bridge.modbus.api.element.WordOrder.LSWMSW;

import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.ConfigurationPolicy;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;
import org.osgi.service.component.annotations.ReferenceCardinality;
import org.osgi.service.component.annotations.ReferencePolicy;
import org.osgi.service.component.annotations.ReferencePolicyOption;
import org.osgi.service.metatype.annotations.Designate;

import io.openems.common.exceptions.OpenemsException;
import io.openems.edge.bridge.modbus.api.AbstractOpenemsModbusComponent;
import io.openems.edge.bridge.modbus.api.BridgeModbus;
import io.openems.edge.bridge.modbus.api.ModbusComponent;
import io.openems.edge.bridge.modbus.api.ModbusProtocol;
import io.openems.edge.bridge.modbus.api.element.FloatDoublewordElement;
import io.openems.edge.bridge.modbus.api.element.SignedWordElement;
import io.openems.edge.bridge.modbus.api.element.UnsignedWordElement;
import io.openems.edge.bridge.modbus.api.task.FC16WriteRegistersTask;
import io.openems.edge.bridge.modbus.api.task.FC3ReadRegistersTask;
import io.openems.edge.bridge.modbus.api.task.FC4ReadInputRegistersTask;
import io.openems.edge.common.component.OpenemsComponent;
import io.openems.edge.common.taskmanager.Priority;

/** AUTO-GENERATED by generator/generate.py - do not edit by hand. */
@Designate(ocd = Config.class, factory = true)
@Component(//
		name = "HeatPump.Idm", //
		immediate = true, //
		configurationPolicy = ConfigurationPolicy.REQUIRE)
public class HeatpumpIdmImpl extends AbstractOpenemsModbusComponent
		implements HeatpumpIdm, ModbusComponent, OpenemsComponent {{

	@Reference
	private ConfigurationAdmin cm;

	@Reference(policy = ReferencePolicy.STATIC, policyOption = ReferencePolicyOption.GREEDY, //
			cardinality = ReferenceCardinality.MANDATORY)
	protected void setModbus(BridgeModbus modbus) {{
		super.setModbus(modbus);
	}}

	public HeatpumpIdmImpl() {{
		super(//
				OpenemsComponent.ChannelId.values(), //
				ModbusComponent.ChannelId.values(), //
				HeatpumpIdm.ChannelId.values() //
		);
	}}

	@Activate
	private void activate(ComponentContext context, Config config) throws OpenemsException {{
		if (super.activate(context, config.id(), config.alias(), config.enabled(), //
				config.modbusUnitId(), this.cm, "Modbus", config.modbus_id())) {{
			return;
		}}
	}}

	@Override
	@Deactivate
	protected void deactivate() {{
		super.deactivate();
	}}

	@Override
	protected ModbusProtocol defineModbusProtocol() {{
		return new ModbusProtocol(this,
{body});
	}}
}}
"""


def synthetic_raw():
    return [{
        "Address": r.address,
        "DataType": r.datatype,
        "Access": r.access,
        "Name": r.name,
        "Unit": r.unit,
        "Min": r.minimum,
        "Max": r.maximum,
        "ValueList": r.value_list,
    } for r in synthetic_registers()]


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_JSON
    raw = load(src) + synthetic_raw()
    regs = [normalize(e) for e in raw if e.get("DataType", "").strip().upper() in TYPE_MAP]
    SRC.mkdir(parents=True, exist_ok=True)
    (SRC / "HeatpumpIdm.java").write_text(gen_interface(regs), encoding="utf-8")
    (SRC / "HeatpumpIdmImpl.java").write_text(gen_impl(regs), encoding="utf-8")
    ro = sum(1 for r in regs if r["access"] == "RO")
    rw = sum(1 for r in regs if r["access"] == "RW")
    w = sum(1 for r in regs if r["access"] == "W")
    print(f"Generiert: {len(regs)} Channels (RO={ro}, RW={rw}, W={w}) aus {src}")


if __name__ == "__main__":
    main()
